# Generated by Django 6.0 on 2025-12-27 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('banco', 'Banco'), ('factory', 'Factory')], max_length=20)),
                ('agencia', models.CharField(blank=True, max_length=20, null=True)),
                ('conta', models.CharField(blank=True, max_length=30, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Conta Financeira',
                'verbose_name_plural': 'Contas Financeiras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('razao_social', models.CharField(blank=True, max_length=200, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MetodoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodos_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoConta',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filhos', to='cadastros.planoconta')),
            ],
            options={
                'verbose_name': 'Plano de Conta',
                'verbose_name_plural': 'Plano de Contas',
                'ordering': ['codigo', 'nome'],
            },
        ),
    ]
