# Generated by Django 6.0 on 2025-12-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contafinanceira',
            name='agencia_dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV Agência'),
        ),
        migrations.AddField(
            model_name='contafinanceira',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV Conta'),
        ),
    ]
