# Generated by Django 6.0 on 2025-12-27 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Pago')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('pago_atrasado', models.BooleanField(default=False, verbose_name='Pago Atrasado')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago')),
                ('classificacao', models.CharField(choices=[('CUSTO', 'Custo'), ('DESPESA', 'Despesa')], default='DESPESA', max_length=10, verbose_name='Classificação')),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Documento')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar_principais', to='cadastros.planoconta', verbose_name='Conta Principal')),
                ('conta_financeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.contafinanceira', verbose_name='Conta Financeira')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_pagar', to='cadastros.fornecedor', verbose_name='Fornecedor')),
                ('metodo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.metodopagamento', verbose_name='Método de Pagamento')),
                ('subconta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar_subcontas', to='cadastros.planoconta', verbose_name='Subconta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_pagar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255, verbose_name='Cliente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('valor_recebido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Recebido')),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Juros')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desconto')),
                ('recebido_atrasado', models.BooleanField(default=False, verbose_name='Recebido Atrasado')),
                ('recebido', models.BooleanField(default=False, verbose_name='Recebido')),
                ('classificacao', models.CharField(choices=[('RECEITA', 'Receita'), ('DEVOLUCAO', 'Devolução')], default='RECEITA', max_length=15, verbose_name='Classificação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber_principais', to='cadastros.planoconta', verbose_name='Conta Principal')),
                ('conta_financeira', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.contafinanceira', verbose_name='Conta Financeira')),
                ('metodo_pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.metodopagamento', verbose_name='Método de Recebimento')),
                ('subconta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber_subcontas', to='cadastros.planoconta', verbose_name='Subconta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-vencimento'],
            },
        ),
        migrations.CreateModel(
            name='MovimentacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('origem', models.CharField(choices=[('MANUAL', 'Lançamento Manual'), ('CONTA_PAGAR', 'Conta a Pagar'), ('CONTA_RECEBER', 'Conta a Receber'), ('TRANSFERENCIA', 'Transferência')], default='MANUAL', max_length=20, verbose_name='Origem')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.planoconta', verbose_name='Categoria')),
                ('conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='cadastros.contafinanceira', verbose_name='Conta Destino')),
                ('conta_financeira', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.contafinanceira', verbose_name='Conta Financeira')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.contapagar', verbose_name='Conta a Pagar')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='financeiro.contareceber', verbose_name='Conta a Receber')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_financeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação Financeira',
                'verbose_name_plural': 'Movimentações Financeiras',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['vencimento'], name='financeiro__vencime_5d47c8_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['pago'], name='financeiro__pago_574963_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['vencimento'], name='financeiro__vencime_85cc76_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['recebido'], name='financeiro__recebid_129935_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_46dfe5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['conta_financeira', '-data'], name='financeiro__conta_f_0c2892_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['tipo'], name='financeiro__tipo_4d6f12_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacaofinanceira',
            index=models.Index(fields=['data'], name='financeiro__data_5d57a6_idx'),
        ),
    ]
