# Generated by Django 6.0 on 2025-12-28 10:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas_receber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Configuração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('codigo_banco', models.CharField(default='104', help_text='104 = Caixa Econômica Federal', max_length=3, verbose_name='Código do Banco')),
                ('codigo_beneficiario', models.CharField(help_text='Fornecido pela Caixa', max_length=20, verbose_name='Código do Beneficiário')),
                ('agencia', models.CharField(max_length=5, verbose_name='Agência')),
                ('agencia_dv', models.CharField(blank=True, max_length=1, verbose_name='DV Agência')),
                ('conta', models.CharField(max_length=12, verbose_name='Conta Corrente')),
                ('conta_dv', models.CharField(max_length=1, verbose_name='DV Conta')),
                ('carteira', models.CharField(default='1', help_text='Carteira de cobrança. Padrão: 1', max_length=2, verbose_name='Carteira')),
                ('modalidade', models.CharField(default='14', help_text='Modalidade de cobrança. Comum: 14', max_length=2, verbose_name='Modalidade')),
                ('convenio', models.CharField(help_text='Número do convênio de cobrança', max_length=20, verbose_name='Número do Convênio')),
                ('nosso_numero_inicio', models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nosso Número Inicial')),
                ('nosso_numero_atual', models.BigIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nosso Número Atual')),
                ('nosso_numero_fim', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nosso Número Final')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('percentual_juros_mes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Juros ao Mês (%)')),
                ('percentual_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Multa (%)')),
                ('dias_para_multa', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Dias para Aplicar Multa')),
                ('dias_para_protesto', models.IntegerField(default=0, help_text='0 = Não protestar', verbose_name='Dias para Protesto')),
                ('dias_para_baixa', models.IntegerField(default=0, help_text='0 = Não baixar automaticamente', verbose_name='Dias para Baixa Automática')),
                ('instrucao1', models.CharField(blank=True, default='Não receber após o vencimento', max_length=100, verbose_name='Instrução 1')),
                ('instrucao2', models.CharField(blank=True, max_length=100, verbose_name='Instrução 2')),
                ('instrucao3', models.CharField(blank=True, max_length=100, verbose_name='Instrução 3')),
                ('local_pagamento', models.CharField(default='PREFERENCIALMENTE NAS CASAS LOTÉRICAS ATÉ O VALOR LIMITE', max_length=100, verbose_name='Local de Pagamento')),
                ('sequencial_arquivo', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sequencial do Arquivo')),
                ('sequencial_lote', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Sequencial do Lote')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Configuração Bancária',
                'verbose_name_plural': 'Configurações Bancárias',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosso_numero', models.CharField(max_length=17, unique=True, verbose_name='Nosso Número')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número do Documento')),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Documento')),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do Desconto')),
                ('valor_abatimento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor do Abatimento')),
                ('valor_mora_dia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Mora/Dia')),
                ('valor_multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor da Multa')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_limite_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Limite para Pagamento')),
                ('data_desconto', models.DateField(blank=True, null=True, verbose_name='Data Limite para Desconto')),
                ('codigo_barras', models.CharField(blank=True, max_length=44, verbose_name='Código de Barras')),
                ('linha_digitavel', models.CharField(blank=True, max_length=54, verbose_name='Linha Digitável')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Emissão'), ('EMITIDO', 'Emitido'), ('REGISTRADO', 'Registrado no Banco'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('VENCIDO', 'Vencido')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('enviado_banco', models.BooleanField(default=False, verbose_name='Enviado ao Banco')),
                ('data_envio_banco', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio ao Banco')),
                ('instrucao1', models.CharField(blank=True, max_length=100, verbose_name='Instrução 1')),
                ('instrucao2', models.CharField(blank=True, max_length=100, verbose_name='Instrução 2')),
                ('mensagem_sacador', models.TextField(blank=True, help_text='Demonstrativo/Descrição do título', verbose_name='Mensagem ao Sacador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contas_receber.cliente', verbose_name='Cliente/Pagador')),
                ('parcela', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleto', to='contas_receber.parcela', verbose_name='Parcela')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletos.configuracaobancaria', verbose_name='Configuração Bancária')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-data_vencimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RemessaCNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sequencial', models.IntegerField(verbose_name='Número Sequencial')),
                ('tipo', models.CharField(choices=[('CNAB240', 'CNAB 240'), ('CNAB400', 'CNAB 400')], default='CNAB240', max_length=10, verbose_name='Tipo')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Arquivo')),
                ('quantidade_titulos', models.IntegerField(default=0, verbose_name='Quantidade de Títulos')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Valor Total')),
                ('status', models.CharField(choices=[('GERADO', 'Gerado'), ('ENVIADO', 'Enviado'), ('PROCESSADO', 'Processado pelo Banco'), ('ERRO', 'Erro no Processamento')], default='GERADO', max_length=20, verbose_name='Status')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('data_envio', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('arquivo_retorno', models.TextField(blank=True, verbose_name='Arquivo de Retorno')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('boletos', models.ManyToManyField(related_name='remessas', to='boletos.boleto', verbose_name='Boletos')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletos.configuracaobancaria', verbose_name='Configuração Bancária')),
            ],
            options={
                'verbose_name': 'Remessa CNAB',
                'verbose_name_plural': 'Remessas CNAB',
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='RetornoCNAB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255, verbose_name='Nome do Arquivo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo do Arquivo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Processamento'), ('PROCESSADO', 'Processado'), ('ERRO', 'Erro no Processamento')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('data_importacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Importação')),
                ('data_processamento', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('quantidade_registros', models.IntegerField(default=0, verbose_name='Quantidade de Registros')),
                ('quantidade_confirmados', models.IntegerField(default=0, verbose_name='Títulos Confirmados')),
                ('quantidade_rejeitados', models.IntegerField(default=0, verbose_name='Títulos Rejeitados')),
                ('quantidade_liquidados', models.IntegerField(default=0, verbose_name='Títulos Liquidados')),
                ('mensagem_erro', models.TextField(blank=True, verbose_name='Mensagens de Erro')),
                ('log_processamento', models.TextField(blank=True, verbose_name='Log de Processamento')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletos.configuracaobancaria', verbose_name='Configuração Bancária')),
                ('remessa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boletos.remessacnab', verbose_name='Remessa Relacionada')),
            ],
            options={
                'verbose_name': 'Retorno CNAB',
                'verbose_name_plural': 'Retornos CNAB',
                'ordering': ['-data_importacao'],
            },
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['nosso_numero'], name='boletos_bol_nosso_n_8f7430_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['status'], name='boletos_bol_status_9782e2_idx'),
        ),
        migrations.AddIndex(
            model_name='boleto',
            index=models.Index(fields=['data_vencimento'], name='boletos_bol_data_ve_46b1d2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='remessacnab',
            unique_together={('configuracao', 'numero_sequencial')},
        ),
    ]
