# Generated by Django 6.0 on 2025-12-28 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaobancaria',
            name='conta_financeira',
            field=models.ForeignKey(blank=True, help_text='Vincular a uma conta financeira cadastrada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.contafinanceira', verbose_name='Conta Financeira'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='agencia',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='agencia_dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV Agência'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='carteira',
            field=models.CharField(blank=True, default='1', help_text='Carteira de cobrança. Padrão: 1', max_length=2, verbose_name='Carteira'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='codigo_beneficiario',
            field=models.CharField(blank=True, help_text='Fornecido pela Caixa', max_length=20, null=True, verbose_name='Código do Beneficiário'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='conta',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Conta Corrente'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='conta_dv',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='DV Conta'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='convenio',
            field=models.CharField(blank=True, help_text='Número do convênio de cobrança', max_length=20, null=True, verbose_name='Número do Convênio'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='modalidade',
            field=models.CharField(blank=True, default='14', help_text='Modalidade de cobrança. Comum: 14', max_length=2, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='nosso_numero_fim',
            field=models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nosso Número Final'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='razao_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social'),
        ),
        migrations.AlterField(
            model_name='configuracaobancaria',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
